--- #YAML:1.0
name:               MojoX-Redis
version:            0.81
abstract:           asynchronous Redis client for L<Mojolicious>.
author:
    - Sergey Zasenko <undef@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.88
requires:
    Mojolicious:      1.22
    Protocol::Redis:  1.0
resources:
    bugtracker:  https://github.com/und3f/mojox-redis/issues
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/und3f/mojox-redis
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
